name: gcu_student_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  barcode_widget: ^2.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: 6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/data/
    # Add assets from the images directory to the application.
    - assets/images/
