name: gcu_student_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  barcode_widget: ^2.0.4
  cached_network_image: ^3.1.0
  url_launcher: ^6.1.11
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: 6.1.1
  camera: ^0.10.5+9
  location: ^5.0.0
  app_settings: ^5.1.1
  image_picker: ^1.0.7
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/data/
    # Add assets from the images directory to the application.
    - assets/images/
