name: gcu_student_app
description: A GCU application for everday student life. This is a hub for all things a student may need on the daily.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  barcode_widget: ^2.0.4
  cached_network_image: ^3.1.0
  url_launcher: ^6.1.11
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: 6.1.1
  camera: ^0.10.5+9
  location: ^5.0.3
  app_settings: ^5.1.1
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^2.0.0

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/data/
    # Add assets from the images directory to the application.
    - assets/images/
